# Generated by Django 6.1.1 on 2026-09-22 19:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., The Patents Act, 1970", max_length=255
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("patent_law", "Patent Law"),
                            ("biodiversity", "Biodiversity & Biological Diversity Act"),
                            ("drug_reg", "Drugs & Cosmetics / AYUSH Regulations"),
                            ("food_reg", "FSSAI / Food & Nutraceutical Regulations"),
                            ("gi", "Geographical Indications (GI)"),
                            ("general_ip", "General IP & Traditional Knowledge (TKDL)"),
                        ],
                        default="patent_law",
                        max_length=50,
                    ),
                ),
                ("jurisdiction", models.CharField(default="India", max_length=100)),
                (
                    "date_enacted",
                    models.DateField(
                        blank=True, help_text="Date or year enacted", null=True
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="Official source link", max_length=500
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("total_chunks", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
