# Generated by Django 6.1.1 on 2026-09-22 19:38

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("chunk_index", models.PositiveIntegerField()),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "section_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=768),
                ),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "document chunk",
                "verbose_name_plural": "document chunks",
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="chunk_embedding_cosine_idx",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
